solbi0802/Algorithm_Study

- Javascript/kNumber.js
채점했더니 85점이 나왔어요.. 테스트에 걸리는 케이스가 존재한다는 건데 리뷰 부탁드립니다 ~
> 프로그래머스 - 정렬) k번째 수 찾기

- Javascript/oddAndEven.js
> [프로그래머스] 짝수와 홀수 문제

- Javascript/minNumber.js
> 세 수 중 최솟값 구하는 문제

- Javascript/triangle.js
> 삼각형 판별하기 문제

- Javascript/sumToN.js
> 1부터 N까지 합 출력하기

- Javascript/reverseNumberArray.js
> [프로그래머스] 자연수 뒤집어 배열로 만들기

- Javascript/AddInteger.js
> [프로그래머스] 음양 더하기

- Javascript/addMatrixNumber.js
> [프로그래머스] 행렬의 덧셈

- Javascript/getDay.js
> [프로그래머스] 2016년 요일 구하기

- Javascript/sortString.js
> [프로그래머스] 문자열 내 마음대로 정렬하기

- Javascript/getMaxOfMatrix.js
오늘도 리뷰 부탁드립니다 :)
그림이 있어서, 캡쳐본도 첨부했습니다.
> 210526 격자판 최대합

- Javascript/getShortestCharDistance.js
> 가장 짧은 문자 거리 구하는 문제

- Javascript/getMaxAndMinNumber.js
> [프로그래머스] 최댓값과 최솟값

- Javascript/mergeTwoArray.js
> 두 배열합치기 문제

- Javascript/removePair.js
> [프로그래머스] 짝지어 제거하기

- Javascript/RemoveParenthesisCharacters.js
> 스택을 이용한 괄호문자 제거하는 문제

- Javascript/calculateInsufficientMoney.js
너무 오랜만에 알고리즘을 풀었네요 
자주 올게요 이제 ㅎㅎ
오늘도 리뷰 부탁드립니다~ :)
> [프로그래머스] 부족한 금액 계산하기

- Javascript/addMissingNumbers.js
> [프로그래머스] 없는 숫자 더하기

- Javascript/findMiddleString.js
가운데 문자 출력하는 문제 풀어봤습니다.
내장함수인 subString 함수를 이용해서 풀어봤어요
> 가운데 문자 출력 문제

- Javascript/deleteDuplicatedString.js
중복 문자 제거하는 문제 풀어봤습니다.
자바스크립트 내장함수인 includes를 사용해서, 
중복된 문자가 아니면 result 변수에 저장해주는 방식으로 풀어봤어요~
> 중복 문자 제거 문제

- Javascript/deleteDuplicatedWord.js
어제 풀이한 방법이랑 동일하게 Set을 사용해서 풀어보았습니다~!
> 중복 단어 제거 문제

- Javascript/findLongestString.js
오랜만에 문제 풀고 리뷰 요청합니다!
가장 긴 문자열을 찾는 문제입니다.
문제 보시면 '각 문자열의 길이는 서로 다릅니다.' 가 있습니다.
가장 긴 문자열의 길이가 같을 수는 없다는 전제 조건이 있는 점 참고 바랍니다.
> 가장 긴 문자열 문제 풀이

- Javascript/extractOnlyNumbers.js
문자와 숫자가 섞여있는 문자열에서 숫자만 추출하는 문제 풀어봤습니다.
간단하게 정규식 써서 풀어봤습니다.
> 숫자만 추출하는 문제

- Javascript/recursionFunctionForBinary.js
지난번에 푼 재귀함수랑 비슷한 문제입니다.
다음 문제부터는 좀 더 난이도 있는 문제로 풀어볼게요!
> 재귀함수를 이용한 이진수 출력

- Javascript/getNumberStrAndWords.js
리뷰 부탁드립니다~!
모르고 마스터에 잘못 올렸다가 다시 브랜치따서 올려서 문제설명이 잘려 있을거에요 
전체 파일 보기로 봐주시면 됩니다!
> [프로그래머스] 숫자 문자열과 영단어
